name: /project/nlp-work7/cargilldujohn-s/Named-Entity-Recognition-using-BERT-with-PyTorch/ner_test
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.0.0
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - arrow-cpp=11.0.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.1.0
  - aws-c-auth=0.6.24
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.11
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.18
  - aws-c-http=0.7.4
  - aws-c-io=0.13.17
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.4
  - aws-c-sdkutils=0.1.7
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.7
  - aws-sdk-cpp=1.10.57
  - blas=2.116
  - blas-devel=3.9.0
  - blinker=1.7.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.2
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.3.101
  - cuda-runtime=12.1.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.8.0.121
  - cycler=0.12.1
  - dataclasses=0.8
  - datasets=2.14.7
  - dbus=1.13.6
  - debugpy=1.8.0
  - decorator=5.1.1
  - dill=0.3.7
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - ffmpeg=4.3
  - fftw=3.3.10
  - filelock=3.13.1
  - flatbuffers=22.12.06
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - fsspec=2023.10.0
  - gast=0.4.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - glog=0.6.0
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - google-auth=2.25.2
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.51.1
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - h5py=3.9.0
  - harfbuzz=6.0.0
  - hdf5=1.14.1
  - huggingface_hub=0.17.3
  - icu=70.1
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.26.0
  - ipython=8.19.0
  - jack=1.9.22
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.1
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.2
  - libarrow=11.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.8.1.2
  - libcups=2.3.3
  - libcurand=10.3.4.101
  - libcurl=8.1.2
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libgoogle-cloud=2.7.0
  - libgpg-error=1.47
  - libgrpc=1.51.1
  - libhwloc=2.9.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libthrift=0.18.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markdown=3.5.1
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.3
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nccl=2.19.4.1
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nettle=3.6
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.96
  - numpy=1.26.2
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.4
  - opt_einsum=3.3.0
  - orc=1.8.2
  - packaging=23.2
  - pandas=2.1.4
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.3.2
  - pixman=0.42.2
  - platformdirs=4.1.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - protobuf=4.21.12
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pyarrow-hotfix=0.6
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pyopenssl=23.3.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.8
  - re2=2023.02.01
  - readline=8.2
  - regex=2023.12.25
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - s2n=1.3.37
  - sacremoses=0.0.53
  - safetensors=0.3.3
  - scipy=1.11.4
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.1.10
  - stack_data=0.6.2
  - sympy=1.12
  - tbb=2021.9.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - tensorflow-gpu=2.11.0
  - termcolor=2.3.0
  - tk=8.6.13
  - tokenizers=0.14.1
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio=2.1.2
  - torchtriton=2.1.0
  - torchvision=0.16.2
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.0
  - transformers=4.35.2
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023d
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - werkzeug=3.0.1
  - wget=1.20.3
  - wheel=0.42.0
  - wrapt=1.16.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
